Repository kaogeek/spanboon, pull requests merged in 2021-01, with the labels that each got.

#43 Add /chatroom/check_unread API
  api-spanboon/src/api/controllers/ChatRoomController.ts
  api-spanboon/src/api/controllers/GuestController.ts
  api-spanboon/src/api/controllers/requests/CheckChatRoomRequest.ts
  api-spanboon/src/api/services/ChatRoomService.ts
  api-spanboon/src/constants/Constants.ts
  api-spanboon/src/constants/SystemConfig.ts
Labels: enhancement

#50 FulfillAllocate Ui
  web-spanboon/src/app/components/pages/main.internal/FanPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/PageHashTag.component.ts
  web-spanboon/src/app/components/pages/main.internal/Redirect.component.ts
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SecurityInfo.component.html
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SecurityInfo.component.ts
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SettingsFanPage.component.html
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SettingsFanPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SettingsInfo.component.html
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SettingsInfo.component.ts
  web-spanboon/src/app/components/pages/main.internal/fulfill.internal/FulfillPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/register.internal/MenuRegister.component.ts
  web-spanboon/src/app/components/shares/card/CardContact.component.html
  web-spanboon/src/app/components/shares/card/CardItem.component.ts
  web-spanboon/src/app/components/shares/chat/ChatMessage.component.ts
  web-spanboon/src/app/services/CheckMessageManager.service.ts
  web-spanboon/src/app/services/facade/PageFacade.service.ts
  web-spanboon/src/app/services/facade/TwitterService.service.ts
Labels: enhancement

#78 ทำ query param allocate/calculate ที่เข้า post ที่ไม่มี objective & e…
  api-spanboon/src/api/controllers/AllocateController.ts
Labels: enhancement

#79 API case/list ให้มี query param เรียงตาม confirm date ล่าสุด
  api-spanboon/src/api/controllers/FulfillmentCaseController.ts
  api-spanboon/src/api/controllers/params/CalculateAllocateQueryparam.ts
  api-spanboon/src/api/services/FulfillmentAllocateStatementService.ts
  api-spanboon/src/constants/FulfillSort.ts
Labels: enhancement

#83 แก้ isRead Message
  api-spanboon/src/api/controllers/ChatController.ts
  api-spanboon/src/api/controllers/ChatRoomController.ts
  api-spanboon/src/api/controllers/requests/CheckChatRoomRequest.ts
  api-spanboon/src/api/models/ChatMessage.ts
  api-spanboon/src/api/services/ChatMessageService.ts
Labels: bug

#84 recalulate isRead by user or Page
  api-spanboon/src/api/controllers/ChatRoomController.ts
  api-spanboon/src/api/controllers/FulfillmentCaseController.ts
  api-spanboon/src/api/controllers/responses/ChatMessageResponse.ts
Labels: bug

#85 PagePost new queryParam from Twitter Post
  api-spanboon/src/api/controllers/ConfigController.ts
  api-spanboon/src/api/controllers/PageController.ts
  api-spanboon/src/api/controllers/PagePostController.ts
  api-spanboon/src/api/controllers/UserController.ts
  api-spanboon/src/api/controllers/requests/ConfigValueRequest.ts
  api-spanboon/src/api/controllers/responses/FulfillmentListResponse.ts
  api-spanboon/src/api/models/PageConfig.ts
  api-spanboon/src/api/models/UserConfig.ts
  api-spanboon/src/api/repositories/PageConfigRepository.ts
  api-spanboon/src/api/repositories/UserConfigRepository.ts
  api-spanboon/src/api/services/PageConfigService.ts
  api-spanboon/src/api/services/PageSocialAccountService.ts
  api-spanboon/src/api/services/TwitterService.ts
  api-spanboon/src/api/services/UserConfigService.ts
  api-spanboon/src/constants/PageConfigs.ts
  api-spanboon/src/constants/UserConfigs.ts
  api-spanboon/src/env.ts
Labels: bug, enhancement

#87 FulfillAllocate
  api-spanboon/.env.production
Labels: enhancement

#88 New API Search for Allocate
  api-spanboon/src/api/controllers/AllocateController.ts
  api-spanboon/src/api/controllers/ChatRoomController.ts
  api-spanboon/src/api/controllers/FulfillmentCaseController.ts
  api-spanboon/src/api/controllers/PageController.ts
  api-spanboon/src/api/controllers/params/SearchAllocateQueryparam.ts
  api-spanboon/src/constants/Constants.ts
Labels: enhancement

#89 Twitter API with Image and PagePostController share image to twitter
  api-spanboon/src/api/controllers/PagePostController.ts
  api-spanboon/src/api/services/AssetService.ts
  api-spanboon/src/api/services/PageSocialAccountService.ts
  api-spanboon/src/api/services/TwitterService.ts
Labels: enhancement

#91 FulfillAllocate
  api-spanboon/src/api/controllers/PagePostController.ts
  api-spanboon/src/api/services/AssetService.ts
  api-spanboon/src/api/services/PageSocialAccountService.ts
  api-spanboon/src/api/services/TwitterService.ts
  web-spanboon/src/app/app-routing.module.ts
  web-spanboon/src/app/components/pages/main.internal/FanPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/LoginPage.component.html
  web-spanboon/src/app/components/pages/main.internal/LoginPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/Policy.component.html
  web-spanboon/src/app/components/pages/main.internal/ProfilePage.component.ts
  web-spanboon/src/app/components/pages/main.internal/register.internal/MenuRegister.component.html
  web-spanboon/src/app/components/pages/main.internal/register.internal/RegisterPage.component.html
  web-spanboon/src/app/components/pages/main.internal/register.internal/RegisterPage.component.ts
  web-spanboon/src/app/components/shares/FulfillItem.component.html
  web-spanboon/src/app/components/shares/FulfillItem.component.ts
  web-spanboon/src/app/components/shares/dialog/DialogPassword.component.html
  web-spanboon/src/app/components/shares/dialog/DialogSettingDateTime.component.html
  web-spanboon/src/app/components/shares/dialog/DialogSettingDateTime.component.ts
  web-spanboon/src/styles/components/pages/main.internal/LoginPage.scss
  web-spanboon/src/styles/components/pages/main.internal/register.internal/MenuRegister.scss
  web-spanboon/src/styles/components/pages/main.internal/register.internal/RegisterPage.scss
  web-spanboon/src/styles/components/shares/FulfillItem.scss
Labels: enhancement
