Repository kaogeek/spanboon, pull requests merged in 2021-08, with the labels that each got.

#262 Dev coffee
  web-spanboon/src/app/components/shares/ManagePage.component.ts
Labels: bug

#270 Dev shiorin
  api-spanboon/src/api/controllers/AssetsController.ts
  api-spanboon/src/api/processors/PostSectionProcessor.ts
Labels: bug

#281 fix bug github
  web-spanboon/src/app/components/pages/main.internal/HomePageV2.component.html
  web-spanboon/src/app/components/pages/main.internal/HomePageV2.component.ts
  web-spanboon/src/app/components/shares/card/CardContentHome.component.html
  web-spanboon/src/app/components/shares/card/CardContentHome.component.ts
  web-spanboon/src/app/components/shares/post/PostData.component.html
Labels: bug

#293 Dev coffee
  web-spanboon/src/app/components/pages/main.internal/FanPage.component.html
  web-spanboon/src/app/components/pages/main.internal/FanPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/PageRecommended.component.html
  web-spanboon/src/app/components/pages/main.internal/PageRecommended.component.ts
  web-spanboon/src/app/components/pages/main.internal/StoryPage.component.html
  web-spanboon/src/app/components/pages/main.internal/StoryPage.component.ts
  web-spanboon/src/app/components/shares/card/CardContentHome.component.ts
  web-spanboon/src/app/components/shares/post/CommentPost.component.ts
  web-spanboon/src/app/components/shares/post/PostData.component.html
  web-spanboon/src/app/components/shares/post/PostData.component.ts
  web-spanboon/src/app/components/shares/tooltip/TooltipProfile.component.html
  web-spanboon/src/app/components/shares/tooltip/TooltipProfile.component.ts
  web-spanboon/src/styles/components/pages/main.internal/FanPage.scss
  web-spanboon/src/styles/components/shares/card/CardContentHome.scss
  web-spanboon/src/styles/components/shares/tooltip/TooltipProfile.scss
Labels: bug, enhancement

#296 #295 add isFollowed to /recommend
  api-spanboon/src/api/controllers/RecommendController.ts
Labels: enhancement
