Repository kaogeek/spanboon, pull requests merged in 2021-02, with the labels that each got.

#92 fix bug Allocate
  web-spanboon/src/app/components/pages/main.internal/StoryPage.component.html
  web-spanboon/src/app/components/pages/main.internal/StoryPage.component.ts
  web-spanboon/src/app/components/shares/dialog/DialogFulfillAllocate.component.html
  web-spanboon/src/app/components/shares/dialog/DialogFulfillAllocate.component.ts
  web-spanboon/src/styles/components/pages/main.internal/fulfill.internal/FulfillAllocatePage.scss
Labels: bug

#102 Twitter share post text generator & Chat Message for Fulfillment Image adding
  api-spanboon/src/api/controllers/FulfillmentCaseController.ts
  api-spanboon/src/api/controllers/PagePostController.ts
  api-spanboon/src/api/models/ChatMessage.ts
  api-spanboon/src/api/services/NeedsService.ts
  api-spanboon/src/constants/ChatMessageTypes.ts
  api-spanboon/src/utils/TwitterUtils.ts
  api-spanboon/src/utils/Utils.ts
Labels: enhancement

#109 Twitter Request Token API
  api-spanboon/src/api/controllers/TwitterController.ts
  api-spanboon/src/api/services/TwitterService.ts
Labels: enhancement

#110 Prevent allocate item into the same post that was allocated.
  api-spanboon/src/api/controllers/AllocateController.ts
  api-spanboon/src/api/controllers/FulfillmentCaseController.ts
  api-spanboon/src/api/controllers/params/CalculateAllocateQueryparam.ts
  api-spanboon/src/auth/authorizationChecker.ts
Labels: enhancement

#118 [Fixed] Confirm allocate statement fulfilled incorrect.
  api-spanboon/src/api/services/FulfillmentAllocateStatementService.ts
Labels: bug

#120 [Fixed] Item mismatch in merge mode
  api-spanboon/src/api/controllers/FulfillmentCaseController.ts
Labels: bug

#123 [Fixed] bug calculate fullfilled field when createFulfillmentAllocateStatement
  api-spanboon/src/api/controllers/PageController.ts
  api-spanboon/src/api/controllers/PagePostController.ts
  api-spanboon/src/api/controllers/PostsController.ts
  api-spanboon/src/api/controllers/requests/PageSocialFBBindingRequest.ts
  api-spanboon/src/api/services/FacebookService.ts
  api-spanboon/src/api/services/FulfillmentAllocateStatementService.ts
  api-spanboon/src/api/services/GoogleService.ts
Labels: bug, enhancement

#124 Add Chat Notifications
  api-spanboon/src/api/services/ChatMessageService.ts
  api-spanboon/src/constants/NotificationType.ts
Labels: enhancement

#125 [Fixed] Cancel confirm allocate_case not update needs
  api-spanboon/src/api/controllers/FulfillmentCaseController.ts
  api-spanboon/src/api/models/FulfillmentRequest.ts
  api-spanboon/src/api/services/FulfillmentAllocateStatementService.ts
  api-spanboon/test/unit/api/controllers/ConfigController.test.ts
  api-spanboon/test/unit/api/services/ConfigService.test.ts
  api-spanboon/test/unit/auth/AuthService.test.ts
Labels: bug

#126 Add chat notification for all page member
  api-spanboon/src/api/services/ChatMessageService.ts
Labels: enhancement

#127 scroll hide browser
  web-spanboon/src/app/components/pages/MainPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/FanPage.component.html
  web-spanboon/src/app/components/pages/main.internal/FanPage.component.ts
  web-spanboon/src/app/components/pages/main.internal/HomePage.component.html
  web-spanboon/src/app/components/pages/main.internal/register.internal/MenuRegister.component.html
  web-spanboon/src/app/components/shares/BoxPost.component.html
  web-spanboon/src/app/components/shares/ControlAction.component.html
  web-spanboon/src/app/components/shares/ControlAction.component.ts
  web-spanboon/src/app/components/shares/Notification.component.html
  web-spanboon/src/app/components/shares/Notification.component.ts
  web-spanboon/src/app/components/shares/card/CardContact.component.ts
  web-spanboon/src/app/components/shares/card/CardItem.component.ts
  web-spanboon/src/app/components/shares/card/NeedsCard.component.ts
  web-spanboon/src/app/components/shares/post/PostData.component.html
  web-spanboon/src/app/components/shares/post/PostData.component.ts
  web-spanboon/src/app/components/shares/post/RepostData.component.html
  web-spanboon/src/app/components/shares/post/RepostData.component.ts
  web-spanboon/src/app/services/CheckMessageManager.service.ts
  web-spanboon/src/styles/components/pages/footer/Footer.scss
  web-spanboon/src/styles/components/pages/header/Header.scss
  web-spanboon/src/styles/components/shares/ControlAction.scss
  web-spanboon/src/styles/components/shares/post/PostData.scss
  web-spanboon/src/styles/components/shares/post/rePostData.scss
Labels: bug

#129 New API /api/page/:id/social/facebook/check
  api-spanboon/src/api/controllers/PageController.ts
Labels: enhancement, help wanted

#131 Do not display the page name.
  web-spanboon/src/app/components/shares/card/CardContact.component.html
Labels: bug

#133 (setting) preload social button
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SecurityInfo.component.html
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SecurityInfo.component.ts
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SettingsFanPage.component.ts
  web-spanboon/src/styles/components/pages/main.internal/fanpage.internal/Security.scss
  web-spanboon/src/styles/variable.scss
Labels: enhancement

#134 fix bug check box social
  web-spanboon/src/app/components/shares/BoxPost.component.html
  web-spanboon/src/app/components/shares/BoxPost.component.ts
  web-spanboon/src/app/components/shares/ControlAction.component.html
  web-spanboon/src/app/models/PageSocialFB.ts
  web-spanboon/src/app/models/PageSocialTW.ts
  web-spanboon/src/app/models/models.ts
  web-spanboon/src/app/services/facade/PageFacade.service.ts
  web-spanboon/src/styles/components/shares/ControlAction.scss
Labels: bug

#136 (notification) not display image
  web-spanboon/src/app/components/shares/Notification.component.html
  web-spanboon/src/app/components/shares/Notification.component.ts
  web-spanboon/src/app/components/shares/chat/ChatMessage.component.html
  web-spanboon/src/app/components/shares/chat/ChatMessage.component.ts
  web-spanboon/src/app/components/shares/pipes/PipeDatetime.pipe.ts
  web-spanboon/src/styles/components/shares/Loading.scss
  web-spanboon/src/styles/components/shares/ManagePage.scss
  web-spanboon/src/styles/components/shares/Notification.scss
  web-spanboon/src/styles/components/shares/dialog/DialogConfirmFulfill.scss
Labels: bug

#138 pattern platform that was published social
  web-spanboon/src/app/components/shares/post/PostData.component.html
  web-spanboon/src/app/components/shares/post/PostData.component.ts
  web-spanboon/src/styles/components/shares/post/PostData.scss
Labels: enhancement

#141 [Job] Facebook Page refresh token every 3 hour.
  api-spanboon/src/api/controllers/JobsController.ts
  api-spanboon/src/api/controllers/PageController.ts
  api-spanboon/src/api/controllers/requests/PageSocialFBBindingRequest.ts
  api-spanboon/src/api/services/FacebookService.ts
  api-spanboon/src/api/services/PageSocialAccountService.ts
  api-spanboon/src/constants/SystemConfig.ts
  api-spanboon/src/loaders/jobSchedulerLoader.ts
Labels: enhancement

#142 Change result of /social/twitter/check and /social/facebook/check
  api-spanboon/src/api/controllers/PageController.ts
  api-spanboon/src/api/controllers/requests/PageSocialFBBindingRequest.ts
  api-spanboon/src/api/controllers/requests/PageSocialTWBindingRequest.ts
  api-spanboon/src/api/models/PageSocialAccount.ts
Labels: enhancement, help wanted

#144 click shared post binding open window new tab
  web-spanboon/src/app/app-routing.module.ts
  web-spanboon/src/app/components/pages/main.internal/Redirect.component.ts
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SecurityInfo.component.html
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SecurityInfo.component.ts
  web-spanboon/src/app/components/pages/main.internal/fanpage.internal/SettingsFanPage.component.ts
  web-spanboon/src/app/components/shares/BoxPost.component.html
  web-spanboon/src/app/components/shares/ManagePage.component.ts
  web-spanboon/src/app/components/shares/Notification.component.html
  web-spanboon/src/app/components/shares/Notification.component.ts
  web-spanboon/src/app/components/shares/card/CardContact.component.html
  web-spanboon/src/app/components/shares/chat/ChatMessage.component.ts
  web-spanboon/src/app/components/shares/post/PostData.component.html
  web-spanboon/src/app/models/PageSocialFB.ts
  web-spanboon/src/app/models/PageSocialTW.ts
  web-spanboon/src/styles/components/pages/main.internal/fanpage.internal/Security.scss
  web-spanboon/src/styles/components/pages/main.internal/fanpage.internal/SettingsInfo.scss
  web-spanboon/src/styles/components/shares/Notification.scss
Labels: enhancement

#145 fix bug binding with pageAccessToken mode
  api-spanboon/src/api/controllers/PageController.ts
  api-spanboon/src/api/controllers/PagePostController.ts
  api-spanboon/src/api/controllers/requests/PageSocialFBBindingRequest.ts
Labels: bug
